//
//  RegisterController.swift
//  PeriodTracker
//
//  Created by Brian Lykes on 11/4/18.
//  Copyright © 2018 Brian Lykes. All rights reserved.
//

import Foundation
import UIKit
import Firebase
import FirebaseAuth
import FirebaseFirestore
import FirebaseDatabase



var ref: DatabaseReference!

class RegisterController: UIViewController {
    //username variable
    @IBOutlet weak var userName: UITextField!
    
    //password variable
    @IBOutlet weak var passWord: UITextField!
    
    //var docRef: DocumentReference!
    override func viewDidLoad() {
        super.viewDidLoad()
       
    }
    
    //TODO: registration functionality
    /// This functin creates the user in Firebase. It takes the variables and connects the to the text fields in the UI.
    /// It also creates a default auth object using Auth.auth() and then calls the create user methods form Firebase to create the user in the auth system.
    /// Error message is displayed if user leaves fields blank.
    /// - Parameter sender: sends userName and passWord as strings
    @IBAction func registerTapped(_ sender: Any) {
       
        if userName.text == "" {
            let alertController = UIAlertController(title: "Error", message: "Please enter email and pass", preferredStyle: .alert)
            let defaultAction = UIAlertAction(title: "OK", style: .cancel, handler: nil)
            alertController.addAction(defaultAction)
            self.present(alertController, animated: true, completion: nil)
            
        } else {
            Auth.auth().createUser(withEmail: userName.text!, password: passWord.text!) { (user, error) in
                
                if error == nil {
                    print ("you have successfully registered")
                    
                    let mainTabController = self.storyboard?.instantiateViewController(withIdentifier: "MainTabController") as! MainTabController
                    self.present(mainTabController, animated: true, completion: nil)
                } else {
                    let alertController = UIAlertController(title: "Error" , message: error?.localizedDescription, preferredStyle: .alert)
                    
                    let defaultAction = UIAlertAction(title: "OK", style: .cancel, handler: nil)
                    alertController.addAction(defaultAction)
                    self.present(alertController, animated: true, completion: nil)
                }
            }
        }
        
        //created refrence variable for database for easier use
        /// MARK: These few lines add the user to the database with an autogenterated ID on the document 
        let ref = Database.database().reference()
        
        //sets user in database with autogenerated document and ID contianing
        //username and other data to be tracked. Username is taken form email field during registration.
        ref.child("users").childByAutoId().setValue(["user": userName.text!, "fertile": 0, "period": 0, "startdate": "_", "cyclelength" : 0, "intimate": true])
    }
 
}
