//
//  RegisterController.swift
//  PeriodTracker
//
//  Created by Brian Lykes on 11/4/18.
//  Copyright © 2018 Brian Lykes. All rights reserved.
//

import Foundation
import UIKit
import Firebase
import FirebaseAuth
import FirebaseFirestore
import FirebaseDatabase




var ref: DatabaseReference!
class RegisterController: UIViewController {
    //username variable
    @IBOutlet weak var userName: UITextField!
    
    //password variable
    @IBOutlet weak var passWord: UITextField!
    
    //var docRef: DocumentReference!
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    //MARK: registration functionality
    /// This functin creates the user in Firebase. It takes the variables and connects them to the text fields in the UI.
    /// It also creates a default auth object using Auth.auth() and then calls the create user methods from Firebase to create the user in the auth system. Calls newUser function which adds user to Firebase RTB
    /// Error message is displayed if user leaves fields blank.
    /// - Parameter sender: sends userName and passWord as strings from text field
    @IBAction func registerTapped(_ sender: Any) {
        newUser() //Function call for adding user to DB
        
        if userName.text == "" {
            let alertController = UIAlertController(title: "Error", message: "Please enter email and pass", preferredStyle: .alert)
            let defaultAction = UIAlertAction(title: "OK", style: .cancel, handler: nil)
            alertController.addAction(defaultAction)
            self.present(alertController, animated: true, completion: nil)
            
        } else {
            Auth.auth().createUser(withEmail: userName.text!, password: passWord.text!) { (user, error) in
                
                if error == nil {
                    print ("you have successfully registered")
                    
                    let mainTabController = self.storyboard?.instantiateViewController(withIdentifier: "MainTabController") as! MainTabController
                    self.present(mainTabController, animated: true, completion: nil)
                } else {
                    let alertController = UIAlertController(title: "Error" , message: error?.localizedDescription, preferredStyle: .alert)
                    
                    let defaultAction = UIAlertAction(title: "OK", style: .cancel, handler: nil)
                    alertController.addAction(defaultAction)
                    self.present(alertController, animated: true, completion: nil)
                }
            }
        }
    }
    
    /// MARK: This function adds the user to the database with an autogenterated ID on the document.
    /// Sets user in database with autogenerated document and ID contianing
    /// username and other data to be tracked. Sets inital values.  Username value is taken form email field during registration.
    func newUser() {
    let ref = Database.database().reference() //created refrence variable for database for easier use
    ref.child("users").childByAutoId().setValue(["user": userName.text!, "fertile": 0, "period": 0, "startdate": "_", "cyclelength" : 0, "intimate": false])
    }

}
